import turtle as t 
t.bgcolor("red")
t.pensize(3)
t.speed(3)
t.color("black")
t.begin_fill()
t.fillcolor("black")
t.left(150)
t.forward(180)
t.circle(-90,180)
t.setheading(60)
t.circle(-90,180)
t.forward(180)
t.end_fill()
t.hideturtle()
msg="     I LOVE YOU "
t.write(msg,move=True, align="left")
Font =(800,"Arial","bold")
t.done()